name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      env:
        ENV_NAME: go-play-env
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      env:
        ENV_NAME: go-play-env
      run: go build -v ./...

    - name: Test
      env:
        ENV_NAME: go-play-env
      run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      
#    - name: Generate coverage report
#      run: |
#        go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage report
      env:
        ENV_NAME: go-play-env
      uses: codecov/codecov-action@v1.2.1
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
